import projetojdbc_dao.ProjetoJdbcDaoExecutar;
import section10.exerciciolista.ExercicioListaExecutar;
import section10.exerciciolistafixacao.ExercicioListaFixacaoExecutar;
import section10.exerciciomatriz.ExercicioMatrizExecutar;
import section10.exerciciomatrizfixacao.ExercicioMatrizFixacaoExecutar;
import section10.exerciciovetorfixacao.VetorExercicioFixacao;
import section10.exerciciovetorparte1.VetorParte1Executar;
import section10.exerciciovetorparte2.VetorParte2Executar;
import section11.trabalhandocomdatas.TrabalhandoComCalendar;
import section11.trabalhandocomdatas.TrabalhandoComDatasExecutar;
import section13.application.EnumTesteExecutar;
import section13.application.PostExecutar;
import section13.application.WorkerExecutar;
import section13.exerciciofixacao.OrderFixacaoExecutar;
import section14.classeabstrata.ClasseAbstrataExecutar;
import section14.heranca.HerancaExecutar;
import section14.heranca.SobreposicaoExecutar;
import section14.metodosabstratos.MetodoAbstratoExecutar;
import section14.metodosabstratosfixacao.MetodoAbstratoFixacao;
import section14.polimorfismo.PolimorfismoExecutar;
import section14.polimorfismofixacao.PolimorfismoFixacaoExecutar;
import section15.ExcecaoExecutar;
import section15.ExcecaoFixacaoExecutar;
import section17.*;
import section17.exerciciofixacao.ArquivosExercicioFixacaoExecutar;
import section18.defaultmethods.DefaultMethodsExecutar;
import section18.exerciciofixacaointerface.ExercicioFixacaoInterfaceExecutar;
import section18.herdarinterface.HerdarInterfaceExecutar;
import section18.interfacecomparable.InterfaceComparableExecutar;
import section18.primeiroexemplo.InterfacePrimeiroExemploExecutar;
import section18.problemaherancamultipla.ProblemaHerancamultiplaExecutar;
import section19.desafiomap.DesafioMapExecutar;
import section19.exemplocuringadelimitado.ExemploCuringDelimitadoExecutar;
import section19.exemplogenericsdelimitados.ExemploGenericsDelimitadosExecutar;
import section19.exemplohashcodeequals.ExemploHashCodeEqualsExecutar;
import section19.exemplomap.ExemploMapExecutar;
import section19.exemploset.ExemploIgualdadeTreeSetExecutar;
import section19.exemploset.ExemploSetExecutar;
import section19.exemploset.ExemploSetIgualdadeExecutar;
import section19.exemplotipocuringa.ExemploTipoCuringaExecutar;
import section19.exerciciofixacaoset.ExercicioFixacaoSetExecutar;
import section19.exercicioset.ExercicioSetExecutar;
import section19.primeiroexemplogenerics.PrimeiroExemploGenericsExecutar;
import section20.exemplocomparator.ExemploComparatorExecutar;
import section20.exemploconsumer.ExemploConsumerExecutar;
import section20.exemplofunction.ExemploFunctionExecutar;
import section20.exemplopredicate.ExemploPredicateExecutar;
import section20.exemplostream.ExemploStreamExecutar;
import section20.exerciciostream.ExercicioStreamExecutar;
import section20.exerciciostreamfixacao.ExercicioStreamFixacaoExecutar;
import section20.funcaocomoargumento.FuncaoComoArgumentoExecutar;
import section6.EstruturaFor;
import section6.EstruturaWhile;
import section7.Funcoes;
import section7.FuncoesString;
import section7.OperadorBitwise;
import section8.execiciometodosestaticos.MetodoEstaticoExecutar;
import section8.exercicioescola.EscolaExecutar;
import section8.exercicioproduto.ProdutoExecutar;
import section9.exerciciomodificadoracesso.BankExecutar;
import section9.sobrecarga.ProductExecutar;

import java.text.ParseException;

public class Main {
    public static void main(String[] args) throws ParseException {

        //SaidaDeDados.executar();
        //SobreCasting.executar();
        //EntradaDeDados.executar();
        //FuncoesMatematicas.executar();
        //EstruturaWhile.executar();
        //EstruturaFor.executar();
        //OperadorBitwise.executar();
        //FuncoesString.executar();
        //Funcoes.executar();
        //ProdutoExecutar.executar();
        //EscolaExecutar.executar();
        //MetodoEstaticoExecutar.executar();
        //ProductExecutar.executar();
        //BankExecutar.executar();
        //VetorParte1Executar.executar();
        //VetorParte2Executar.executar();
        //VetorExercicioFixacao.executar();
        //ExercicioListaExecutar.executar();
        //ExercicioListaFixacaoExecutar.executar();
        //ExercicioMatrizExecutar.executar();
        //ExercicioMatrizFixacaoExecutar.executar();
        //TrabalhandoComDatasExecutar.executar();
        //TrabalhandoComCalendar.executar();
        //EnumTesteExecutar.executar();
        //WorkerExecutar.executar();
        //PostExecutar.executar();
        //OrderFixacaoExecutar.executar();
        //HerancaExecutar.executar();
        //SobreposicaoExecutar.executar();
        //PolimorfismoExecutar.executar();
        //PolimorfismoFixacaoExecutar.executar();
        //ClasseAbstrataExecutar.executar();
        //MetodoAbstratoExecutar.executar();
        //MetodoAbstratoFixacao.executar();
        //ExcecaoExecutar.executar();
        //ExcecaoFixacaoExecutar.executar();
        //LerArquivoComScannerExecutar.executar();
        //FileReaderAndBufferedReaderExecutar.executar();
        //FileWriterAndBufferedWriterExecutar.executar();
        //ManipularPastaComFileExecutar.executar();
        //InformacoesFileExecutar.executar();
        //ArquivosExercicioFixacaoExecutar.executar();
        //InterfacePrimeiroExemploExecutar.executar();
        //ExercicioFixacaoInterfaceExecutar.executar();
        //HerdarInterfaceExecutar.executar();
        //ProblemaHerancamultiplaExecutar.executar();
        //InterfaceComparableExecutar.executar();
        //DefaultMethodsExecutar.executar();
        //PrimeiroExemploGenericsExecutar.executar();
        //ExemploGenericsDelimitadosExecutar.executar();
        //ExemploTipoCuringaExecutar.executar();
        //ExemploCuringDelimitadoExecutar.executar();
        //ExemploHashCodeEqualsExecutar.executar();
        //ExemploSetExecutar.executar();
        //ExemploSetIgualdadeExecutar.executar();
        //ExemploIgualdadeTreeSetExecutar.executar();
        //ExercicioSetExecutar.executar();
        //ExercicioFixacaoSetExecutar.executar();
        //ExemploMapExecutar.executar();
        //DesafioMapExecutar.executar();
        //ExemploComparatorExecutar.executar();
        //ExemploPredicateExecutar.executar();
        //ExemploConsumerExecutar.executar();
        //ExemploFunctionExecutar.executar();
        //FuncaoComoArgumentoExecutar.executar();
        //ExemploStreamExecutar.executar();
        //ExercicioStreamExecutar.executar();
        //ExercicioStreamFixacaoExecutar.executar();
        ProjetoJdbcDaoExecutar.executar();
    }
}
