import section10.exerciciolista.ExercicioListaExecutar;
import section10.exerciciolistafixacao.ExercicioListaFixacaoExecutar;
import section10.exerciciomatriz.ExercicioMatrizExecutar;
import section10.exerciciomatrizfixacao.ExercicioMatrizFixacaoExecutar;
import section10.exerciciovetorfixacao.VetorExercicioFixacao;
import section10.exerciciovetorparte1.VetorParte1Executar;
import section10.exerciciovetorparte2.VetorParte2Executar;
import section11.trabalhandocomdatas.TrabalhandoComCalendar;
import section11.trabalhandocomdatas.TrabalhandoComDatasExecutar;
import section13.application.EnumTesteExecutar;
import section13.application.PostExecutar;
import section13.application.WorkerExecutar;
import section13.exerciciofixacao.OrderFixacaoExecutar;
import section14.classeabstrata.ClasseAbstrataExecutar;
import section14.heranca.HerancaExecutar;
import section14.heranca.SobreposicaoExecutar;
import section14.metodosabstratos.MetodoAbstratoExecutar;
import section14.metodosabstratosfixacao.MetodoAbstratoFixacao;
import section14.polimorfismo.PolimorfismoExecutar;
import section14.polimorfismofixacao.PolimorfismoFixacaoExecutar;
import section15.ExcecaoExecutar;
import section15.ExcecaoFixacaoExecutar;
import section17.*;
import section17.exerciciofixacao.ArquivosExercicioFixacaoExecutar;
import section18.defaultmethods.DefaultMethodsExecutar;
import section18.exerciciofixacaointerface.ExercicioFixacaoInterfaceExecutar;
import section18.herdarinterface.HerdarInterfaceExecutar;
import section18.interfacecomparable.InterfaceComparableExecutar;
import section18.primeiroexemplo.InterfacePrimeiroExemploExecutar;
import section18.problemaherancamultipla.ProblemaHerancamultiplaExecutar;
import section6.EstruturaFor;
import section6.EstruturaWhile;
import section7.Funcoes;
import section7.FuncoesString;
import section7.OperadorBitwise;
import section8.execiciometodosestaticos.MetodoEstaticoExecutar;
import section8.exercicioescola.EscolaExecutar;
import section8.exercicioproduto.ProdutoExecutar;
import section9.exerciciomodificadoracesso.BankExecutar;
import section9.sobrecarga.ProductExecutar;

import java.text.ParseException;

public class Main {
    public static void main(String[] args) throws ParseException {

        //SaidaDeDados.executar();
        //SobreCasting.executar();
        //EntradaDeDados.executar();
        //FuncoesMatematicas.executar();
        //EstruturaWhile.executar();
        //EstruturaFor.executar();
        //OperadorBitwise.executar();
        //FuncoesString.executar();
        //Funcoes.executar();
        //ProdutoExecutar.executar();
        //EscolaExecutar.executar();
        //MetodoEstaticoExecutar.executar();
        //ProductExecutar.executar();
        //BankExecutar.executar();
        //VetorParte1Executar.executar();
        //VetorParte2Executar.executar();
        //VetorExercicioFixacao.executar();
        //ExercicioListaExecutar.executar();
        //ExercicioListaFixacaoExecutar.executar();
        //ExercicioMatrizExecutar.executar();
        //ExercicioMatrizFixacaoExecutar.executar();
        //TrabalhandoComDatasExecutar.executar();
        //TrabalhandoComCalendar.executar();
        //EnumTesteExecutar.executar();
        //WorkerExecutar.executar();
        //PostExecutar.executar();
        //OrderFixacaoExecutar.executar();
        //HerancaExecutar.executar();
        //SobreposicaoExecutar.executar();
        //PolimorfismoExecutar.executar();
        //PolimorfismoFixacaoExecutar.executar();
        //ClasseAbstrataExecutar.executar();
        //MetodoAbstratoExecutar.executar();
        //MetodoAbstratoFixacao.executar();
        //ExcecaoExecutar.executar();
        //ExcecaoFixacaoExecutar.executar();
        //LerArquivoComScannerExecutar.executar();
        //FileReaderAndBufferedReaderExecutar.executar();
        //FileWriterAndBufferedWriterExecutar.executar();
        //ManipularPastaComFileExecutar.executar();
        //InformacoesFileExecutar.executar();
        //ArquivosExercicioFixacaoExecutar.executar();
        //InterfacePrimeiroExemploExecutar.executar();
        //ExercicioFixacaoInterfaceExecutar.executar();
        //HerdarInterfaceExecutar.executar();
        //ProblemaHerancamultiplaExecutar.executar();
        //InterfaceComparableExecutar.executar();
        DefaultMethodsExecutar.executar();
    }
}
